config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'

  devise_for :users, controllers: {
        registrations: 'users/registrations'
  }
  namespace :users do
    get 'favorite_courses' => 'favorite_courses#show'
    post 'favorite_courses' => 'favorite_courses#create'
    delete 'favorite_courses' => 'favorite_courses#destroy'
    post 'favorite_courses/export' => 'favorite_courses#export'

    get 'passed_courses' => 'passed_courses#show'
    post 'passed_courses' => 'passed_courses#create'
    delete 'passed_courses' => 'passed_courses#destroy'

    get 'time_filter' => 'time_filter#show'
    patch 'time_filter' => 'time_filter#update'
    put 'time_filter' => 'time_filter#update'
    post 'time_filter/import' => 'time_filter#import'
  end

  resources :courses, only: [:index, :show] do
    post :vote, on: :member
    post :title, on: :collection
    post :instructor, on: :collection
  end

  resources :comments, only: [:create, :update, :destroy] do
    post :vote, on: :member
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  # Record versioning
  has_paper_trail only: [:content],
                  on: [:create, :destroy, :update],
                  meta: { user_id: :user_id,
                          course_id: :course_id,
                          parent_id: :parent_id }

  # Has many relationships
  has_many :votes, as: :votable

  # Belongs to these models
  belongs_to :user
  belongs_to :course, touch: true

  # Self association
  has_many :replies, -> { order(:created_at) }, class_name: 'Comment',
            foreign_key: 'parent_id', dependent: :destroy
  belongs_to :parent, class_name: 'Comment',
              foreign_key: 'parent_id', optional: true

  validates :content, length: { maximum: 1000 }, presence: true
  validates_presence_of :course, :user
  validates_presence_of :parent, unless: -> { parent_id.nil? }
  validate :check_parent_course_id, unless: -> { parent.nil? }

  scope :thread, -> { where(parent: nil) }

  before_create :generate_avatar

  def generate_avatar
    self[:avatar] = Digest::MD5.hexdigest("#{course_id}-#{user.secure_random}")
  end

  def check_parent_course_id
    if parent.course_id != course_id
      errors.add(:course_id, 'id不相符')
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include ActionVoter

  before_action :authenticate_user!
  before_action :find_comment, only: [:update, :destroy]

  def create
    @comment = current_user.comments.new(comment_params)
    if @comment.save
      @new_comment = Comment.new
      if @comment.parent_id.nil?
        render 'courses/comments/created'
      else
        render 'courses/comments/replies/created'
      end
    else
      render json: { error: @comment.errors.full_messages }, status: 500
    end
  end

  def update
    if @comment.update(comment_params)
      render json: @comment.as_json(only: [:id, :content, :updated_at])
    else
      render json: { error: @comment.errors.full_messages }, status: 500
    end
  end

  def destroy
    if @comment.destroy
      render json: @comment.as_json(only: [:id])
    else
      render json: { error: @comment.errors.full_messages }, status: 500
    end
  end

  def vote
    comment = Comment.find(params[:id])
    vote_for(comment, params[:upvote])
  end

  private

  def find_comment
    @comment = current_user.comments.find(params[:id])
  end

  def comment_params
    params_allowed = [:content]
    params_allowed << :course_id << :parent_id if action_name == 'create'
    params.require(:comment).permit(params_allowed)
  end
end

app/views/courses/comments/replies/_form.html.slim
.reply-block.collapse id="#{comment.id}_comment_form"
  = form_for [course, @new_comment], url: comments_path, remote: true, html: {id: "new_reply_on_#{comment.id}"} do |f|
    = f.hidden_field :course_id, value: course.id
    = f.hidden_field :parent_id, value: comment.id
    = f.text_area :content, class: 'form-control', onkeyup: 'autoheight(this)', placeholder: '我想說...'
    = f.button :submit, class: 'btn btn-block' do
      i.fa.fa-paper-plane
      | 留言

app/views/courses/comments/replies/_index.html.slim
.reply-list.collapse.in id="#{comment.id}_comment_reply"
  = render partial: 'courses/comments/replies/reply', collection: comment.replies, cache: true

app/views/courses/comments/replies/_reply.html.slim
.replies.clearfix id="#{reply.id}_comment" itemprop="comment" itemscope=true itemtype="http://schema.org/Comment"
  meta itemprop="dateCreated" content="#{reply.created_at.utc.iso8601}"
  .avatar
      = image_tag avatar_path(reply), class: 'img-responsive'
  - if is_author?(reply)
    .options.dropdown.vote.text-right
      a.dropdown-toggle href='#' type='button' id='dropdownEditOptions' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'
        i.fa.fa-caret-down
      ul.dropdown-menu aria-labelledby='dropdownEditOptions'
        li
          a.reply-edit-button href='#'
            i.fa.fa-pencil
            | 編輯
        li
          = link_to reply, method: :delete, remote: true, class: "btn-delete-comment", data: { confirm: '確定刪除？' } do
            i.fa.fa-remove
            | 刪除
          
  .reply-content
    .text itemprop="text"
      = simple_format reply.content, data: {resource: :comment, url: comment_path(reply.id), name: :content}
    .vote
      span.date data-date="#{reply.created_at.utc.iso8601}"
      span
        | &ensp;&#8901;&ensp;
        = link_to vote_comment_path(id: reply.id, upvote: true), method: :post, remote: true, class: "btn-vote-reply #{vote_status(reply, true)}" do
          i.fa.fa-chevron-up
        span id="rank_on_reply_#{reply.id}" = "#{reply.score}|#{reply.votes_count}"
        = link_to vote_comment_path(id: reply.id, upvote: false), method: :post, remote: true, class: "btn-vote-reply #{vote_status(reply, false)}" do
          i.fa.fa-chevron-down

app/views/courses/comments/replies/created.js.slim
// Trigger Reset Action on Corresponding Form to Clear Form
| $("#new_reply_on_#{@comment.parent_id}").trigger('reset');
| autosize.update($("#new_reply_on_#{@comment.parent_id} > textarea"));

// Update Replies Count of Corresponding Parent Object
| $("span#replies_count_on_#{@comment.parent_id}").html("#{@comment.parent.replies.size}&nbsp;則回覆&ensp;");

// Render Newly Created Comments
| content = $("##{@comment.parent_id}_comment_reply").append("
= j render 'courses/comments/replies/reply', reply: @comment
| ");
| $('body').animate({scrollTop: $("##{@comment.id}_comment_reply").position().top}, 800);

// Processing Relative Time
| $('##{@comment.parent_id}_comment_reply .date').each(function() {
|  var date = $(this).data('date');
|  var date_formatted = moment(date).startOf('minute').fromNow();
|  $(this).text(date_formatted);
|});