config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'

  devise_for :users, controllers: {
        registrations: 'users/registrations'
  }
  namespace :users do
    get 'favorite_courses' => 'favorite_courses#show'
    post 'favorite_courses' => 'favorite_courses#create'
    delete 'favorite_courses' => 'favorite_courses#destroy'
    post 'favorite_courses/export' => 'favorite_courses#export'

    get 'passed_courses' => 'passed_courses#show'
    post 'passed_courses' => 'passed_courses#create'
    delete 'passed_courses' => 'passed_courses#destroy'

    get 'time_filter' => 'time_filter#show'
    patch 'time_filter' => 'time_filter#update'
    put 'time_filter' => 'time_filter#update'
    post 'time_filter/import' => 'time_filter#import'
  end

  resources :courses, only: [:index, :show] do
    post :vote, on: :member
    post :title, on: :collection
    post :instructor, on: :collection
  end

  resources :comments, only: [:create, :update, :destroy] do
    post :vote, on: :member
  end

end

app/views/common/_flash.html.erb
<div class="alert alert-dismissable alert-<%= type %>">
  <% if dismissable %>
    <button type="button" class="close" data-dismiss="alert">×</button>
  <% end %>
  <strong><%= message %></strong>
</div>

app/views/common/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="col-sm-2 col-sm-push-10 share-btn">
      <a href="https://www.facebook.com/CourseNote"><i class="fa fa-facebook"></i></a>
      <a href="https://github.com/atitan/coursenote"><i class="fa fa-github"></i></a>
    </div>
    <div class="col-sm-10 col-sm-pull-2">
      <p>
        <span>Copyright &copy; atitan, and all contributors.</span>
        <span>Code released under the <a href="http://opensource.org/licenses/MIT">MIT License</a>.</span>
      </p>
      <p>
        <span>Based on <a href="http://getbootstrap.com" rel="nofollow">Bootstrap</a>. </span>
        <span>Icons from <a href="http://fortawesome.github.io/Font-Awesome/" rel="nofollow">Font Awesome</a>. </span>
        <span>Web fonts from <a href="http://www.google.com/webfonts" rel="nofollow">Google</a>.</span>
      </p>
    </div>
  </div>
</footer>

app/views/common/_github.html.erb
<span id="forkongithub">
  <a href="https://github.com/atitan/coursenote">Fork me on GitHub</a>
</span>

app/views/common/_navbar.html.erb
<nav class="navbar-fixed-top" data-no-turbolink>
  <div class="container">
    <h1><a href="/">中原選課大全</a><span class="sr-only">導覽列</span></h1>
    <span class="navbar-text visible-xs visible-sm">(<%= @last_entry.strftime("%g%m%d-%H%M") %>)</span>
    <span class="navbar-text visible-md visible-lg visible-xl">最後更新：<%= @last_entry.strftime("%F %R") %></span>
    <button class="nav-btn visible-xs">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <ul class="nav-list text-right">
      <li class="nav-item hover-effect"><%= link_to '課程查詢', courses_path %></li>
      <li class="nav-item hover-effect"><a href="https://www.facebook.com/CourseNote" target="_blank">粉絲專頁</a></li>
      <li class="nav-item hover-effect"><a href="/old_coursenote.json" target="_blank">舊版選課大全資料</a></li>
      <% if user_signed_in? %>
        <li class="dropdown nav-item">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="themes"><%= current_user.email %> <span class="caret"></span></a>

          <ul class="dropdown-menu" aria-labelledby="themes">
            <li><%= link_to '已追蹤課程', users_favorite_courses_path%></li>
            <li><%= link_to '已修過課程', users_passed_courses_path%></li>
            <li><%= link_to '空堂時間表', users_time_filter_path%></li>
            <li><%= link_to '更改密碼', edit_user_registration_path%></li>
            <li><%= link_to '登出', destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      <% else %>
        <li class="nav-item hover-effect"><%= link_to '登入', new_user_session_path %></li>
        <li class="nav-item hover-effect"><%= link_to '註冊', new_user_registration_path %></li>
      <% end %>
    </ul>

  </div>
</nav>